### ISSUE TITLE
Bot not transferring faucets

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [5ire-org/5ire-faucet#12]
I have used the bot before to get 5 5ire coins

But recently from 3-4 days its not sending any coins to the testnet account address.
It just says sending but it never actually sends.

Attaching screenshot for better transparency ;

![image](https://user-images.githubusercontent.com/41825906/168486661-8f4ef38f-0d3c-446b-95ca-42a00852b4a3.png)

**Comment by dung5ire** [comment]
Hi thanks for update ! we will consider this issues. Can you show your test-net account ? and which endpoint do you connect?

**Comment by Shubham-Kumar-2000** [comment]
Yes
![image](https://user-images.githubusercontent.com/41825906/168589384-3bbeef8c-dd89-45fe-818e-bede22de6af6.png)

I use `shiva.testnet.5ire.network`

**Comment by dung5ire** [comment]
yeah , we got it. I think you should use develop mode first by `./target/build/release --dev`. We are trying fix it.

**Comment by Shubham-Kumar-2000** [comment]
where do i need to run this command
??

**Comment by dung5ire** [comment]
hi @Shubham-Kumar-2000 , 5ireChain is working now. You can check it again

**Comment by Shubham-Kumar-2000** [comment]
Yes thank you
